### ISSUE TITLE
Unification of Ledgers

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#2579]
## Context

Massa core currently contains two different Ledgers:

### FinalLedger

- Is in `massa-ledger` (good)
- Exclusively used in `massa-final-state` which is interacted with in `massa-execution-worker` (good)
- Has a corresponding SpeculativeLedger (good)
- Stored on RAM (bad)
- Only operations applied to it are SC operations (bad)

### Ledger

- Is in `massa-graph` (bad)
- Exclusively used in `massa-graph` (bad)
- Stored on Disk (good)
- All the operations except SC operations are applied to it (bad)

### Unification

If you look closely, you can see that these 2 ledger complete themselves, what isn't great about one, the other has.
The goal is therefore to unify them, which is specified in the TODO list below.

### What we currently use for disk storage

[Sled](https://docs.rs/sled/latest/sled/), a pure rust embedded database.

### What [NEAR](https://github.com/near) uses

The NEAR blockchain uses a similar stack to what we use. They also had to solve the issue of saving blockchain data on Disk using rust. The crate choice they've made for that matter is [rust-rocksdb](https://github.com/rust-rocksdb/rust-rocksdb), which is a rust binding crate for the well known [RocksDB](https://github.com/facebook/rocksdb).

### Sled vs RockDB

The only advantage that Sled has over RockDS is that it is pure rust, it is slower, has less features, and is not as maintained as RocksDB.

You can check a benchmark comparison here: https://github.com/tokahuke/sled-vs-rocksdb

### TODO

- [x] Decide if we wish to use RocksDB instead of Sled for Disk storage
- [x] Move `massa-graph` ledger to `massa-ledger`
- [x] ~Save a ledger per thread in `massa-ledger` to match `massa-graph` ledger (feels like it's the best solution but is it?)~
- [x] Keep the execution block finality and save only one ledger
- [x] Store and interact with `massa-ledger` on Disk
- [x] Update the speculative ledger corresponding to the new unified ledger
- [x] Define how we'll implement the ledger updates on rolls operations (ask PoS module for the infos?)

## Related discussions, issues and PR's

- [__Ledger unification RFC__](https://github.com/massalabs/massa/blob/ledger_unif_doc/docs/rfc_ledger_unif.md)
- https://github.com/massalabs/massa/issues/2644
- https://github.com/massalabs/massa/issues/2342
- https://github.com/massalabs/massa/pull/2590
- https://github.com/massalabs/massa/pull/2761
- https://github.com/massalabs/massa/pull/2727

**Comment by damip** [comment]
OK let's go for rust-rocksdb

**Comment by damip** [comment]
done for v14
