### ISSUE TITLE
Do not allow any interaction with RockDB crate outside of LedgerDB

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#2638]
## Context

The current implementation of the disk ledger operations batching requires `massa-ledger/ledger.rs` to import RockDB types, we want to have everything wrapped inside of `massa-ledger/ledger_db.rs`.

## TODO (Only after intermediate bootstrap is replaced by streaming)

- [x] Move `FinalLedger::apply` code into `LedgerDB` in the form of `apply_changes_at`
- [x] Handle all the write operations in `apply_changes_at`
- [x] Handle the metadata update in `apply_changes_at`
- [x] Use only `apply_changes_at` in `FinalLedger`
