### ISSUE TITLE
Move blockgraph ledger to massa-ledger

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#2644]
## Context

The execution ledger has been recently moved to disk storage using RocksDB. The blockgraph ledger must be part of the same object and use the same storage method.

## TODO

- [x] Define how PoS will be handled
- [x] Move blockgraph ledger code to `massa-ledger`
- [x] Adapt the code so it is compatible with the execution ledger (can update this later for a more detailed description)
- [x] Use `ledger_db` instead of sled for disk storage

**Comment by Eitu33** [comment]
https://github.com/massalabs/massa/pull/2699/

**Comment by AurelienFT** [comment]
@Eitu33 this could be closed ?

**Comment by Eitu33** [comment]
Yes indeed, done in https://github.com/massalabs/massa/pull/2862. Closing.
