### ISSUE TITLE
Add a rust representation of disk ledger keys

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#2660]
## Context

- Disk ledger keys are currently handled as byte vectors, example in [get_ledger_part](https://github.com/massalabs/massa/blob/main/massa-ledger/src/ledger_db.rs#L439) return type
- It would be better to have a rust representation of disk ledger keys

## TODO

- [ ] Define the `KeyType` enum
- [ ] Define the `Key` type, should contain a `KeyType` and an `Address`
- [ ] Implement Ser & Deser
- [ ] Replace occurrences of byte vectors keys in [`ledger_db.rs`](https://github.com/massalabs/massa/blob/feature/stream_bootstrap/massa-ledger/src/ledger_db.rs), [massa-bootstrap](https://github.com/massalabs/massa/tree/feature/stream_bootstrap/massa-bootstrap/src) `client.rs`, `server.rs` with `Key`'s

**Comment by AurelienFT** [comment]
Done in #3455
