### ISSUE TITLE
Split massa-ledger (exports / worker)

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#2681]
## Context

See https://github.com/massalabs/massa/issues/2342#issuecomment-1149706929

## TODO

- [x] Move externally used structs to `massa-ledger-exports`
- [x] Move worker code to `massa-ledger-worker`
- [x] Have RocksDB dep only in modules that import `massa-ledger-worker`
