### ISSUE TITLE
Lazily query sub-entries in the speculative ledger

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#2696]
## Context

The speculative ledger currently accumulates the changes of the whole active history. It would be a great performance improvement and a good setup for the API enhancement to make it so that the speculative ledger lazily queries sub-entries through active history when it has a need for them.

## TODO

- [ ] Directly take the active history as input in the speculative ledger (define which way is the best suited) instead of the accumulated changes
- [ ] Implement lazy sub-query searching functions
- [ ] Use the named functions when in need of a ledger value
