### ISSUE TITLE
Use the ledger hash to draw selections

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#2985]
## Introduction

This is the second issue for the implementation of https://github.com/massalabs/massa/discussions/2968

## TODO

- [ ] Save a snapshot of the ledger hash in PoS at every end of cycle
- [ ] Concat the C-2 seed with the C-3 ledger hash
- [ ] Use this as new seed when drawing selections

## Related issues

https://github.com/massalabs/massa/issues/2986

**Comment by damip** [comment]
Ideally, we should use the hash of the whole state (not only the ledger)

**Comment by AurelienFT** [comment]
Closed in #2986
