### ISSUE TITLE
Save and update the ledger hash on disk

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#2986]
## Introduction

This is the first issue for the implementation of https://github.com/massalabs/massa/discussions/2968

## TODO

- [x] Save the ledger hash on disk
- [x] Concat the slot hash to the ledger hash
- [x] Update the hash on every write operation of the `ledger_db` module
- [x] Update the `ledger_db` tests accordingly

## Related issues

https://github.com/massalabs/massa/issues/2985
