### ISSUE TITLE
Add Smart Contract ABI to use operation datastore

### ISSUE THREAD

**Issue by sydhds** [massalabs/massa#3001]
## Intro

2nd issue for RFC SC Datastore: https://github.com/massalabs/massa/discussions/2970

## Todo

- [ ] Add ABI in massa-sc-std
- [ ] Add related function in massa-sc-runtime
- [ ] Add related function in massa-execution-*

**Comment by damip** [comment]
@sydhds that's done right ?

**Comment by sydhds** [comment]
> @sydhds that's done right ?

Already done! Closing it.
