### ISSUE TITLE
Error from rust world to assemblyscript world

### ISSUE THREAD

**Issue by sydhds** [massalabs/massa#3005]
## Intro

Currently there is no way for a function executed in the Rust world to return an error that we could deal with in the assemblyscript world.
For now, if there is an error in the Rust world, the function just panics (aka bail!) but sometimes we could want to propagate the error and let the SC code deals with the error.

## Todo

- [ ] Explore and read about errors in AssemblyScripts
- [ ] Find a function that require this (idea: getOpKeys())
- [ ] Implement the error propagation

**Comment by modship** [comment]
possible solution to consider : https://docs.wasmer.io/integrations/examples/exit-early 
other resources :https://rustwasm.github.io/wasm-bindgen/reference/types/result.html

**Comment by AurelienFT** [comment]
> possible solution to consider : https://docs.wasmer.io/integrations/examples/exit-early
I believe this is the other direction. For this direction we already have the `abort` in AS.

**Comment by AurelienFT** [comment]
As we are already returning error from Rust to AS maybe it's more on the run team side to check for it ? Can I have your toughts @sydhds and @Ben-Rey ?

**Comment by sydhds** [comment]
From what I remember, the goal was to have an abi function returning a Result<T, Error> and have it handled in the Smart contact so in AS code we will have something like:

`
let res: Result<i32, ASError> = call_abi_XX(...);
if res.is_err() {
    ...
    print("Abi call fail so we will use another method...");
}
`

Not sure to remember what was the use case :-/

**Comment by Ben-Rey** [comment]
Could it be related to: https://github.com/massalabs/massa-as-sdk/issues/127

**Comment by AurelienFT** [comment]
Yes we have all our ABI currently returning Results but they are not handled on the AS side I think it's something totally related to AS there is nothing we could do on runtime we already returning errors.

**Comment by modship** [comment]
I think it's more clear with the example in github : https://github.com/wasmerio/wasmer/blob/master/examples/early_exit.rs

Need to test if wasm module gets ExitCode

**Comment by AurelienFT** [comment]
> I think it's more clear with the example in github : https://github.com/wasmerio/wasmer/blob/master/examples/early_exit.rs
> 
> Need to test if wasm module gets ExitCode

As I said here: https://github.com/massalabs/massa/issues/3005#issuecomment-1440438582 I think this is from Guest -> Host error propagation that we already have with `abort` in AS. This issue speaks about the other side Host -> Guest

**Comment by modship** [comment]
yes i understood the request, 
if i understand correctly the example of early_exit; the wasm module call a function of the host that return an Error.

**Comment by Ben-Rey** [comment]
We can move the issue on the AS side. It could be related to other problems such as: https://github.com/massalabs/massa-as-sdk/issues/127

**Comment by sydhds** [comment]
> 

Abi return results but the error part of those results are handled in Rust side; what I said was having something like:

Result<Result<...>> so a "Result" is given to AS and handled it in SC code. Problem is how to do that

**Comment by AurelienFT** [comment]
Do you have the doc or line that say that this result is managed in the Host side ?

**Comment by sydhds** [comment]
A abi proto: pub(crate) fn assembly_script_get_remaining_gas(mut ctx: FunctionEnvMut<ASEnv>) -> ABIResult<i64> { ... }

whereas in AS code the proto is:

@external("massa", "assembly_script_get_remaining_gas")
export declare function remainingGas(): u64;

The idea would be to have in AS code as a proto:

export declare function myFunction(): Result<u64, string>;

**Comment by damip** [comment]
Covered by https://github.com/massalabs/massa-sc-runtime/issues/246
