### ISSUE TITLE
Tests: easy build

### ISSUE THREAD

**Issue by sydhds** [massalabs/massa#3045]
## Intro

A lot of unit test use wasm file built from small AssemblyScript files. We can found those in the following repo:

* massa (example: massa/massa-execution-worker/src/tests/wasm/sources/execution_error/main.ts)
* massa-sc-runtime: (example: massa-sc-runtime/wasm/src/caller.ts)

There are no easy way to build these wasm files for now (especially for Rust dev).

## Todo

- [x] Create a new repo (massa-unit-tests-src ?) with everything to build asc (using the new massa-as-sdk)
- [x] Move src into this new repo
- [x] Add a Doc (how to setup / build / ...)
- [x] Add a CI where we auto build the wasm files and ideally propose a PR in the appropriate repo to update the wasm file (to avoid desync)

**Comment by damip** [comment]
perfect !

**Comment by qdrn** [comment]
The CI in the [massa-sc-template](https://github.com/massalabs/massa-sc-template) repository build a minimal helloworld example.

**Comment by AurelienFT** [comment]
Done in : https://github.com/massalabs/massa/pull/3150
