### ISSUE TITLE
State hash

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#3059]
## Introduction

We need to have a way to compare the states of two different nodes, this has already been done for ledger in https://github.com/massalabs/massa/issues/2986 but needs to be done for the rest of the `FinalState`

## TODO

On finality:
- [x] Compute and save ledger hash
- [x] Compute and save async pool hash
- [x] Compute and save PoS state hash
- [x] Compute and save executed ops hash
- [x] Hash the concat of every part of the final state together to deduce the final state hash
- [x] Update PoS selections system using the global hash as seed

**Comment by damip** [comment]
@Eitu33 for the executed ops hash (and state hashes in general), it is important that the hashes are computed only at the final state. Computing them for speculative states would have a strong performance impact (and they are not needed there)

**Comment by Eitu33** [comment]
Taking back this issue

**Comment by Eitu33** [comment]
* https://github.com/massalabs/massa/pull/3210
* https://github.com/massalabs/massa/pull/3312

**Comment by Eitu33** [comment]
This is done, closing
