### ISSUE TITLE
Identify performance bottlenecks in testnet 14

### ISSUE THREAD

**Issue by damip** [massalabs/massa#3061]
Locate performance bottlenecks in testnet 14.

* [x] evaluate the performance of signature verification: https://github.com/massalabs/massa/issues/3071
* [x] many storage manipulations in Execution https://github.com/massalabs/massa/issues/3069
* [ ] peer exchange performance in Network https://github.com/massalabs/massa/issues/3070

**Comment by AurelienFT** [comment]
[perf.txt](https://github.com/massalabs/massa/files/9631362/perf.txt)

**Comment by damip** [comment]
> [perf.txt](https://github.com/massalabs/massa/files/9631362/perf.txt)

That's an old one (has secp256k1 stuff).

Here is the new one: [perf.txt](https://github.com/massalabs/massa/files/9632446/perf.txt)

**Comment by damip** [comment]
Perf for 2 minutes under 1000 txps load, compiled with --release: https://we.tl/t-fQI5O7jQB1
