### ISSUE TITLE
Add a way for a client to specify operation datastore 

### ISSUE THREAD

**Issue by sydhds** [massalabs/massa#3072]
## Intro

In massa-client, there is currently no way to specify an operation datastore when using the command read_only_smart_contract.

## Todo

- [ ] Find a way to specify key / value (or the entire datastore)
  - [ ] Maybe in 2 ways: by key: value one by one or via a file (but which format?)
- [ ] Implement this in massa-client, file cmds.rs

**Comment by damip** [comment]
This applies to:
* read-only executions
* ExecuteSC calls

**Comment by damip** [comment]
I think this will be limited to API access, because allowing the user to specify binary stuff in the REPL is not practical
