### ISSUE TITLE
Use messages serialization in bootstrap

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#3145]
## Introduction

Current bootstrap treats raw data for the whole final state when it only makes sense for the ledger to stream raw data because of its format.

## TODO

- [x] Change Async Pool bootstrap streaming
- [x] Change PoS bootstrap streaming
- [x] Change Executed Ops bootstrap streaming
