### ISSUE TITLE
Fix execution test scenarios

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#3338]
## Context

After the recent changes of runtime and the test SCs code, a few execution test scenarios do not pass anymore

## TODO

- [x] Investigate if those test issues are expected
- [x] If they are fix the tests
- [x] If they are not open a bug issue
