### ISSUE TITLE
Massa gRPC API V2

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa#3377]
This issue tracks the work in progress on the newer Massa JsonRPC API.

Refactor the API:

1 - Specify the business needs with Core, the Innovation team, direct users (eg. Dusa) and the community Builders. Try to split endpoints as much as possible. Use snake_case everywhere (https://github.com/massalabs/massa/pull/2823). Decide if we fuse the private/public APIs and allow finer access control through other means.

2 - Write a new API that uses https://github.com/hyperium/tonic crate and will support the following features:
  * [x] Schema reflection (introspection). See https://github.com/hyperium/tonic/blob/master/tonic-reflection/tests/server.rs
  * [x] Support Http 1.1 transport. See https://github.com/hyperium/tonic/blob/master/tonic-web/README.md
  * [x] Limit size of message(s). See https://github.com/hyperium/tonic/issues/1097
  * [x] Support gateway annotations. See https://github.com/hyperium/tonic/issues/332
  * [ ] Support Json instead of Protobuf. See https://github.com/hyperium/tonic/blob/master/examples/src/json-codec/common.rs
  * [x] Support of service health check. See https://github.com/hyperium/tonic/blob/master/tonic-health/README.md
  * [x] Support mTLS. #3815
  * [ ] Support client authorizations via #4315
  * [x] Postman gRPC client with Massa collection. See https://www.postman.com/massalabs
  * [x] Support bulk(batch) methods
  * [x] Add better logging in the gRPC API
  * [ ] Support WebSocket binding to gRPC streaming. See https://github.com/massalabs/massa/discussions/2895 and stream events for SC applications (@BatiGencho)
  * [ ] Support rate limiting https://github.com/benwis/tower-governor
  * [x]  Support custom Tokio runtime
  * Support pagination. See [paginate](https://docs.rs/paginate/latest/paginate) crate #3428
  * [x] Full configuration support from Massa config system #3600
  * [x] Build a CI/CD around `.proto` files #3622. See https://github.com/massalabs/massa-proto
  * [x] Force minimal version of `protoc` in `build.rs`. See https://github.com/datafuselabs/databend/blob/main/src/meta/protos/build.rs
  * [x]  Migrate massa core to use [massa-proto-rs](https://github.com/massalabs/massa-proto-rs) #4050
  * [x] Add `serialized_size` field to `SecureShares` in APIs #4019

3 - Let's also add the following endpoints:
* [x] SendEndrosments #3423 
* [x] SendOperations #3642
* [x] SentBlocks  #3420 
* [x] GetSelectorDraws #3421 
* [x] GetNextBlockBestParents #3419
* GetLatestBlock
* GetLatestOperation
* GetLatestEndorsement
* [x] GetBlocksBySlots #3425
* GetExecutedOperations
* GetLargestWallet #3427
* GetLargestStakers #3485
* [x] GetTransactionsThroughput #3426
* [x] GetBalances #3813
* GetSlots (need by Inno: slot ID, ASC execution and its gas consumption, deferred credits and its gas consumption, and block object and its gas consumption, since they have different gas limits) #3593
* GetRolls
* [x] GetHealth already done implicitly 
* GetStakingActivation
* GetStakingInfos
* GetTokenInfos
* [x] GetBlocks #3839
* [x] GetOperations  #3835
* SimulateOperations already exists 
* [x] GetVersion
* [x]  GetDatastoreEntries #3621
* [x]  GetScExecutionEvents #3867

4 - As well as streaming methods for:
* [x] NewBlocks
* [x] NewBlocks_headers
* [x] NewFilledBlocks
* [x] NewOperations
* [x]  NewEndorsements #3833
* NewBlockCliques #3857
* [x]  NewSlotExecutionOutputs #3810
* [x]  NewTransactionsThroughput #3426
* [x]  NewStateEventsChanges #3812

Existing WebSockets should be migrated to equivalent gRPC streams.

There is a [discussion](https://github.com/massalabs/massa/discussions/3406) about gRPC support.
This will pave the way towards https://github.com/massalabs/massa/issues/2903 in particular, and also help @BatiGencho with execution event streaming for web3.

previously #2799 #3076

**Comment by aoudiamoncef** [comment]
Hi @massalabs/core-team, 

As we are going to accelerate the development of Massa API V2, we are gathering all enhancements proposals in this issue.

Based on clients feedbacks, I made the list of methods/subscriptions/features above, we should select, drop and prioritise what's really add a value to Massa.

I'm waiting for feedbacks, feel free to update and/or comment issue.

Thanks 👍🏻

**Comment by banool** [comment]
I see you have ticked off "Support gateway annotations", how are you planning to implement that given it isn't supported in the underlying libraries?

**Comment by aoudiamoncef** [comment]
Hi @banool 

We added gateway annotations in our gRPC service definition to be used by reverse proxies Eg [Envoy](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter) and other languages E.g in [go](https://grpc-ecosystem.github.io/grpc-gateway/)

In the future, if Prost/Tonic adds support for a Rust based gateway, we're already ready.
