### ISSUE TITLE
Bootstrap improvements tracking issue

### ISSUE THREAD

**Issue by Ben-PH** [massalabs/massa#3746]
For launch of main-net, Improvements to the bootstrap server are one of our many priorities. This issue should serve as reference to smaller tasks/tracking issues.

To take a work-item, create an issue, edit that item to include the issue number, and if it's a PR, do the link-thing.

 - [ ] async-specific issues
    - [x] make the listen/accept methods non-async #3685 
    - [x] make the message sending non-async #3745 
    - [x] remove requirement for async entirely - only async is a `block_on` with a network-sender fn
    - [x] remove tokio dependency - #3796 
    - [x] Reintroduce the bootstrap-process timeout. #3821 
    - [x] Check if we still need the `Duplex` trait at all - try to use `std::net::TcpStream` directly, and mock that
    - [x] restore timeout behavior (before: timeout on an `.await`. post 3745: per tcp read/write call #3821 
    - [ ] reinstate bandwidth limiters
    - [x] #3905 

- [ ] tests
  - [ ] use mocked clients to test server saturation
  - [ ] use mocked clients to test holding onto a connection for too long
  - [ ] test timeout behavior on where `tokio::timeout` was previously used
  

- [ ] Setup benchmarking

- [ ] General improvements
  - [x] remove `[allow(clippy::result_large_err)]` for `BootstrapError` returns, e.g. by using `Box` on variants its variants: #3751 
  - [x] Where possible, use `peek` and/or other techniques to join multiple `read/write_exact` calls into the one call. #3772 #3774
  - [x] cleanup error management - #3757
  - [ ] Investigate encapsulating the BS state in the type-system (e.g. pre/post handshake, mid send/recv, etc.) #3804 
  - [ ] Don't depend on msg-recv timeout at start of `fn bootstrap_from_server`
  - [x] [restore bootstrapping time-limit](https://github.com/massalabs/massa/pull/3782/files?diff=unified&w=1#diff-2f2a0d279d4c015c632b27bdc7bd2fb62cf753fa8811dead19aadc3133666156L474-R460) (removed by #3782)
  - [x] Don't use dedicated thread for listening (must be sig-int/ctrl-c compatible) #3780 
  - [x] use consts directly via a module instead of fields of struct variables #3881 
  - [x] read-loop instead of read-exact #3885

**Comment by modship** [comment]
>   * [ ]  remove `[allow(clippy::result_large_err)]` for `BootstrapError` returns, e.g. by using `Box` on variants its variants`

it is only used in `white_black_list.rs` and all error are boxed. He can be removed without clippy error.

**Comment by Ben-PH** [comment]
There are a lot of places in #3745 that are of type `Rusult<T, BootstrapError>`, and that triggers a clippy lint that is fixed by making it `Result<T, Box<BootstrapError>>`, but that's... not so nice.

**Comment by modship** [comment]
> There are a lot of places in #3745 that are of type `Rusult<T, BootstrapError>`, and that triggers a clippy lint that is fixed by making it `Result<T, Box<BootstrapError>>`, but that's... not so nice.

Ok 👍🏼 i have look at #3685

**Comment by damip** [comment]
Don't block CTRL-C when waiting to retry bootstrap from another node

**Comment by Ben-PH** [comment]
https://github.com/massalabs/massa/pull/3905

**Comment by Ben-PH** [comment]
#3931 will fix main, based on #3905, using only code changes core to the ctrl-c issue.

**Comment by Ben-PH** [comment]
This has bloated up quite a lot. Creating fresh tracking issue that tracks back to this one: #3972
