### ISSUE TITLE
Clear HD module cache when restarting a node

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#3912]
## Context

We have been experiencing unexpected issues after restarting a node when it previously cached a given set of SC modules. Clearing it is our best option here as the HD cache is not deterministic anyway.

## TODO

- [x] check for existing RocksDB info when initializing the HD cache
- [x] clear it if present
- [x] test the case

**Comment by AurelienFT** [comment]
Done in #3915
