### ISSUE TITLE
Bootstrap work tracking issue pt2

### ISSUE THREAD

**Issue by Ben-PH** [massalabs/massa#3972]
Follow up from issue #3746 #3890 #3842

 - [x] reinstate bandwidth limiters #4059 
 - [ ] Investigate encapsulating the BS state in the type-system (e.g. pre/post handshake, mid send/recv, etc.) #3804 
 - [ ] Don't depend on msg-recv timeout at start of `fn bootstrap_from_server`
 - [x] use consts directly via a module instead of fields of struct variables #3881 
 - [x] review privacy of bootstrap types
 - [x] test relaunch of of bootstrap server following desynchro: (#3970)
 - [x] restore ctrlc handling: [3c50962](https://github.com/massalabs/massa/pull/3876/commits/3c50962ab49356792398c6af6d5a35661d649f66) #3971 
 - [ ] restore windows testing in CI (where to even _start?_)
 - [ ] de-constify when reading the next message
 - [ ] sort out a clean (de)serialization/state update when getting next messages
 - [ ] regression test: handle flooded FDs in the event loop.
 
 test possibilities
 
 - [ ] desynchro leading to re-bootstrap
 - [ ] too many clients
 - [ ] clients on for too long
 - [x] timeout triggers #4079 
 - [ ]
