### ISSUE TITLE
get_operation_id meta issue

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#4219]
## Context

see https://github.com/massalabs/massa-sc-runtime/issues/272

## TODOs

* [x] massa: https://github.com/massalabs/massa/pull/4218
* [x] massa-sc-runtime: https://github.com/massalabs/massa-sc-runtime/pull/276
* [x] massa-as-sdk: https://github.com/massalabs/massa-as-sdk/pull/278
* [x] port the previous changes to testnet_25
* [x] implement the ABI on the new runtime with protos: https://github.com/massalabs/massa-sc-runtime/issues/279

**Comment by Eitu33** [comment]
I know but it's not right that why I didn't use it

**Comment by Eitu33** [comment]
Everything has been done, closing
