### ISSUE TITLE
TESTNET 26 CHECKLIST

### ISSUE THREAD

**Issue by damip** [massalabs/massa#4352]
* [ ] proto-rs: fix https://github.com/massalabs/massa-proto-rs/issues/27
* [ ] sc-runtime: update dependency on proto-rs
* [ ] sc-runtime: merge https://github.com/massalabs/massa-sc-runtime/pull/300
* [ ] sc-runtime: add https://github.com/massalabs/massa/issues/4295
* [ ] sc-runtime: cargo update

* [ ] massa: update dependency to proto-rs
* [ ] massa: update dependency to massa-sc-runtime
* [ ] massa: make sure that https://github.com/massalabs/massa/issues/4295 works
* [ ] massa: finish https://github.com/massalabs/massa/pull/4314
* [ ] massa: fix https://github.com/massalabs/massa/issues/4345
* [ ] massa: fix https://github.com/massalabs/massa/issues/4340
* [ ] massa: fix https://github.com/massalabs/massa/issues/4338
* [ ] massa: fix missing in https://github.com/massalabs/massa/issues/4288

* [ ] massa: cargo update
