### ISSUE TITLE
Node security meta-issue

### ISSUE THREAD

**Issue by damip** [massalabs/massa#4415]
## Functional tests

The goal of functional tests is to run a network of nodes and interact with them to check if consensus is properly achieved, that the network propagates data correctly etc...

Tasks:
* [x] k8s cluster deployment @aoudiamoncef
* [x] connection of the python test framework with the node cluster @sydhds 
* [ ] implement operation and block propagation tests under flood
* [ ] #4456
* [ ] load tests with objects of exactly the maximum allowed sizes and beyond
* [ ] fuzzing
* [ ] try bootstrapping with large ledgers @litchipi 

## Unit tests and code review

* [ ] General considerations
  * [x] #4396
  * [ ] #4450 @aoudiamoncef 
  * [ ] aim for a test coverage above 80% if possible https://github.com/massalabs/massa/issues/4418
  * [x] update to rust 1.72.1 (fixes some CVEs)
* [ ] fix all tagged security issues: https://github.com/massalabs/massa/labels/Security%20team%20input
* [ ] Models 
  * [ ] for all object deserializations (coming from the API, from network, or from bootstrap)
    * [ ] check size limits  @damip 
    * [ ] endure that direct bracket accesses are always safe (eg. `buffer[i+3:]` will panic if i is too big)  @damip 
    * [ ] write unit tests with objects/arrays of exactly the maximum allowed sizes 
* [ ] Protocol/network @modship
  * [ ] audit the code to ensure safe operation
  * [ ] implement unit tests with various connect/disconnect/flood scenarios
  * [ ] calibrate bandwidth limits 
* [ ] #4430
  * [ ] ensure that a bootstrapping client can not make a bootstrap server panic by sending invalid data
  * [ ] make sure a client cannot deny service by staying connected too long or flooding
  * [ ] implement unit tests for those aspects
  * [ ] calibrate bandwidth limits and timeout values
* [ ] API @modship 
  * [ ] ensure that no inputs to the API will make the system panic nor stay locked for a lot of time (input checks, length checks)
  * [ ] implement API unit tests with edge cases for each public API endpoint #4426 
* [ ] Consensus
  * [ ] Check which parts are not covered by unit test coverage and cover them  @Leo-Besancon 
* [ ] Execution @damip  
  * [ ] audit code
  * [ ] calibrate gas for transaction/roll_buy/roll_sell operations
  * [ ] add unit tests on coin spending edge cases
* [] Final State
  * https://github.com/massalabs/massa/issues/4435
