### ISSUE TITLE
SC execution gas costs

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#4483]
## Problem summary

We have multiple issues concerning gas costs and how we handle them in operations and ABIs related to smart-contracts.

## Current and target behaviours

|                          | CURRENT              | TARGET                      | CHANGED  |
|--------------------------|----------------------|-----------------------------|  :---:   |
| **CallSC (OP)**          |                      |                             |          |
| compilation              | NOT PAID             | NOT PAID                    |          |
| VM instantiation         | NOT PAID             | PAID IN MAX_GAS (UNIFIED CONSTANT)  | *|
| module instantiation     | PAID IN MAX_GAS OR COMPILATION_GAS | PAID IN MAX_GAS       | *|
| execution                | PAID IN MAX_GAS      | PAID IN MAX_GAS             |          | 
| **ExecuteSC (OP)**       |                      |                             |          |
| compilation              | PAID IN MAX_GAS      | PAID IN MAX_GAS             |          |
| VM instantiation         | NOT PAID             | PAID IN MAX_GAS (UNIFIED CONSTANT)  | *|
| module instantiation     | PAID IN MAX_GAS OR COMPILATION_GAS | PAID IN MAX_GAS       | *|
| execution                | PAID IN MAX_GAS      | PAID IN MAX_GAS             |          |
| **Call (ABI)**           |                      |                             |          |
| compilation              | NOT PAID             | NOT PAID                    |          |
| VM instantiation         | PAID IN ABI GAS      | PAID IN CALL GAS (UNIFIED CONSTANT) | *|
| module instantiation     | PAID IN ABI GAS      | PAID IN CALL GAS            |         *|
| execution                | PAID IN CALL GAS     | PAID IN CALL GAS            |          |
| base gas cost of the ABI | PAID IN ABI GAS      | PAID IN ABI GAS             |          |
| **LocalExecution (ABI)** |                      |                             |          |
| compilation              | NOT PAID             | PAID IN CALL GAS            |         *|
| VM instantiation         | PAID IN ABI GAS      | PAID IN CALL GAS (UNIFIED CONSTANT) | *|
| module instantiation     | PAID IN ABI GAS      | PAID IN CALL GAS            |         *|
| execution                | PAID IN CALL GAS     | PAID IN CALL GAS            |          |
| base gas cost of the ABI | PAID IN ABI GAS      | PAID IN ABI GAS             |          |
| **CreateSC (ABI)**       |                      |                             |          |
| compilation              | PAID IN ABI GAS      | PAID IN ABI GAS             |          |
| **SetBytecode (ABI)**    |                      |                             |          |
| compilation              | PAID IN ABI GAS      | PAID IN ABI GAS             |          |

## TODOs

- [x] Calibrate Cranelift compilation cost
- [x] Calibrate Singlepass compilation cost
- [x] Calibrate max instance cost
- [x] Use max instance cost as an initial unified constant cost for all SC executions
- [x] Use instance cost as points for initial cache instances
- [x] Reduce ABIs cost to a minimal as execution cost will be deducted from the call gas
- [x] Pay compilations where they should be paid (see above)
- [x] Document what is paid where

## Follow-ups

* https://github.com/massalabs/massa/issues/4484

**Comment by Eitu33** [comment]
# Calibration

## Specs

```
Model Name:                 MacBook Pro
Model Identifier:           MacBookPro18,3
Chip:	                    Apple M1 Pro
Total Number of Cores:	    8 (6 performance and 2 efficiency)
Memory:	                    16 GB
System Firmware Version:    7429.61.2
OS Loader Version:          7429.61.2
Serial Number (system):	    Y7R07XFPHG
Hardware UUID:	            EDC5DCA2-F669-5BF4-8601-A38CCA7098A9
Provisioning UDID:          00006000-0012481E26D2801E
Activation Lock Status:	    Enabled
```

## Compilation results (on average)

* 5000 "classic" operations: 107 ms
* CL compilation (1 MO SC): 19 ms
* SP compilation (1 MO SC): 8 ms

## Compilation gas values

* CL compilation: (4,2 * 10^9) / (107 / 19) = 746 million gas (745 794 392)
* SP compilation: (4,2 * 10^9) / (107 / 8) = 314 million gas (314 018 691)

## Max instance gas value

Ideal proposition was to allow a maximum of 2000 instances in one slot so:

(4,2 * 10^9) / 2000 = 2.1 million gas

In my instance limit tests, the further I reached was 300 000 gas. I do believe we could take more time to measure this, but it looks like a good first limit.

**Comment by bilboquet** [comment]
# Calibration
## Specs
same as https://github.com/massalabs/massa/issues/4467
```
cpu:      AMD Ryzen 7 PRO 6850U
nb cores: 8 physical (16 logical)
RAM:      32 GB
uname -a: Linux fedora 6.5.5-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Sep 24 15:52:44 UTC 2023 x86_64 GNU/Linux
```

## Compilation results (on average)

- 5000 transactions: 84.5 ms
- CL compilation (1 MO SC): XXX ms
- Mean SP compilation time (1 MO SC): 7 ms
<details>
<summary>SP compilation raw measures</summary>

 sp compilation took 8057 μs
 sp compilation took 7425 μs
 sp compilation took 6797 μs
 sp compilation took 7262 μs
 sp compilation took 6921 μs
 sp compilation took 6712 μs
 sp compilation took 8223 μs
 sp compilation took 6666 μs
 sp compilation took 7362 μs
 sp compilation took 7049 μs
 sp compilation took 7872 μs
 sp compilation took 6980 μs
 sp compilation took 7046 μs
 sp compilation took 7759 μs
 sp compilation took 6836 μs
 sp compilation took 6627 μs
 sp compilation took 6535 μs
 sp compilation took 6513 μs
 sp compilation took 6502 μs
 sp compilation took 7238 μs
 sp compilation took 7164 μs
 sp compilation took 6789 μs
 sp compilation took 7154 μs
 sp compilation took 6446 μs
 sp compilation took 6694 μs
 sp compilation took 7258 μs
 sp compilation took 6246 μs
 sp compilation took 6522 μs
 sp compilation took 6518 μs
 sp compilation took 7289 μs
 sp compilation took 7370 μs
 sp compilation took 7064 μs
 sp compilation took 8462 μs
 sp compilation took 6658 μs
 sp compilation took 7104 μs
 sp compilation took 6735 μs
 sp compilation took 6796 μs
 sp compilation took 6575 μs
 sp compilation took 6737 μs
 sp compilation took 6892 μs
 sp compilation took 7138 μs
 sp compilation took 6657 μs
 sp compilation took 6580 μs
 sp compilation took 6569 μs
 sp compilation took 7351 μs
 sp compilation took 7588 μs
 sp compilation took 6639 μs
 sp compilation took 7645 μs
 sp compilation took 6918 μs
 sp compilation took 6969 μs
 sp compilation took 6950 μs
 sp compilation took 6914 μs
 sp compilation took 6794 μs
 sp compilation took 6603 μs
 sp compilation took 6470 μs
 sp compilation took 6483 μs
 sp compilation took 6914 μs
 sp compilation took 6578 μs
 sp compilation took 6767 μs
 sp compilation took 7443 μs
 sp compilation took 6824 μs
 sp compilation took 6429 μs
 sp compilation took 6620 μs
 sp compilation took 6718 μs
 sp compilation took 6583 μs
 sp compilation took 6818 μs
 sp compilation took 6651 μs
 sp compilation took 6797 μs
 sp compilation took 6534 μs
 sp compilation took 6857 μs
 sp compilation took 6630 μs
 sp compilation took 6687 μs
 sp compilation took 7883 μs
 sp compilation took 6890 μs
 sp compilation took 6529 μs
 sp compilation took 7463 μs
 sp compilation took 7727 μs
 sp compilation took 7413 μs
 sp compilation took 6460 μs
 sp compilation took 6778 μs
 sp compilation took 6609 μs
 sp compilation took 6499 μs
 sp compilation took 6390 μs
 sp compilation took 6764 μs
 sp compilation took 6799 μs
 sp compilation took 6811 μs
 sp compilation took 6905 μs
 sp compilation took 7138 μs
 sp compilation took 6808 μs
 sp compilation took 6731 μs
 sp compilation took 8007 μs
 sp compilation took 6909 μs
 sp compilation took 6757 μs
 sp compilation took 6561 μs
 sp compilation took 6499 μs
 sp compilation took 6606 μs
 sp compilation took 6737 μs
 sp compilation took 6320 μs
 sp compilation took 7181 μs
 sp compilation took 6569 μs
</details>
