### ISSUE TITLE
Unify SC executions

### ISSUE THREAD

**Issue by Eitu33** [massalabs/massa#4484]
## Context

As some were described in https://github.com/massalabs/massa/issues/4483, we have similar behaviours between operations and ABIs that are related to smart contracts execution. This type of execution is complex and must take into consideration multiple factors, it would be a great addition for maintainability if we could unify this. 

At the moment operations and ABIs don't treat this in the exact same way, but it should possible to unify it.

## TODOs

- [ ] Try to unify similar parts of ExecuteSC (OP) and LocalExecution (ABI)
- [ ] Try to unify similar parts of CallSC (OP) and Call (ABI)
- [ ] Look into other possible candidates
